### ISSUE TITLE
There was an error accessing Spotify's Web API. 

### ISSUE THREAD

**Issue by drone-snapper** [JMPerez/spotify-dedup#171]
There was an error accessing Spotify's Web API. Please try again later. If the problem persist, please file an issue on https://github.com/JMPerez/spotify-dedup/issues/

**Comment by niccelery** [comment]
same issue here. I haven't been able to use the site for a long time. I assume its because I have too many liked songs (48k)

**Comment by cl-jae** [comment]
Hello, the website works again for me when my liked song are under 23K, above it doesn't work anymore. Hope it helps ^^"

**Comment by JMPerez** [comment]
Hi folks,

I have worked recently on improving the error handling of the app to make it more resilient to issues in Spotify’s API. I have written about the changes on https://buymeacoffee.com/jmp/spotify-dedup-enhancing-reliability-user-experience in case you want to read more about it.

The error message that was referred to in this GitHub issue was a generic one that didn’t provide much information but helped me start to track the errors. It’s very likely that the underlying problem has been fixed after my changes.

Since this error message is not shown in the app anymore, I’m closing this issue and I suggest you to file an issue if you encounter any problems, with the specific message that is shown, and any additional information that helps identify the problem (Spotify user name, what action was being performed, browser name, etc.)

**Comment by mattperry1976** [comment]
I am also still having this issue continually now for the past several days
